version: '3.8'

services:
  # 服务 1: 你的 FastAPI 应用
  api:
    build: .  # 使用当前目录的 Dockerfile 构建
    container_name: soft-robot-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/robot_data
    depends_on:
      - db
    networks:
      - robot-network

  # 服务 2: 数据库 (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: soft-robot-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=robot_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - robot-network
  # ✅ 新增: 数据库管理界面
  adminer:
    image: adminer
    container_name: soft-robot-adminer
    ports:
      - "8080:8080"  # 浏览器访问 8080 -> 容器内部 8080
    networks:
      - robot-network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  robot-network: